Feature/1204104076708648 add pallet vesting integraton tests
peaqnetwork/peaq-bc-test pull request #12
Opened 2023-03-07 17:02 UTC by sayyed-kamran

The purpose of this feature branch is to add integration tests for pallet_vesting. Please review.

2023-03-08 10:19 UTC, sfffaaa requested changes

2023-03-08 10:19 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +    vest_test(KP_TARGET_FIRST)
After sending Vesting.vest, should we check something more, for example, account/event/chain state or something more?

2023-03-08 10:19 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +    vest_other_test(KP_TARGET_SECOND, KP_SUDO)
After sending Vesting. vest_other, should we check something more, for example, account/event/chain state or something more? Or we can verify whether the extrinsic works or not.

2023-03-08 10:19 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +def pallet_vesting_test():
The logic you have here is:
vested_transfer --> force_vested_transfer --> vest --> vest_other --> merge_test

I think we can make the test logic clearer by separating your test log into three different test cases
1. vested_transfer --> vest
2. force_vested_transfer --> vest_other
3. merge_test

Usually, one test case (test function here) has only one primary testing purpose. In your case, one test case has three parts (vest_test, vest_other_test, and merge_schedule_test). It's not a good practice and is hard to maintain. Therefore, please refine this function to make it clearer.

2023-03-09 14:50 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +    vest_other_test(KP_TARGET_SECOND, KP_SUDO)
Updated the code by including an assert statement that will compare locked balance before vest  with locked balance after vest. Here we will use: 

assert locked_balance_before_vest > locked_bal_after_vest. 

We can  not make an exact comparison like
assert locked_balance_before_vest - locked_bal_after_vest = vested_transfer_amount

Since, we are not sure, if there are some other vested balance available in the same account that is also eligible to be released. (vesting.vest_other will release any amount that  is locked and is eligible to be released)

2023-03-09 16:01 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +def pallet_vesting_test():
Currently my test cases has following inter dependencies:

The test case vest_test() is dependent on vest_transfer_test().

The test case vest_other_test() is dependent on forced_vest_test().

merge_schedule_test() is independent. 

Now I can adopt two approaches.

First approach:
To group the test cases in the same order  so that a dependent test case will be executed immediately after its parent

1. vested_transfer --> vest
2. force_vested_transfer --> vest_other
3. merge_test

Second Approach:
More ever, we can make five  test cases fully independent too. in such case, we will need to create an independent  vested_transfer extrinsic  within the test case vest  and similarly a vested_transfer extrinsic within the vest_other_test.  Just like I created a new independent extrinsic in the test case merge_schedule_test(). 

For now I am going to adopt the first approach. In case you want me to adopt the second one. Please let me know.

2023-03-10 09:47 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +    vest_test(KP_TARGET_FIRST)
How about creating the new key pair and then starting the testing process? Is it helpful? Because we can make sure there is no other vested balance available.

2023-03-10 09:47 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +    vest_other_test(KP_TARGET_SECOND, KP_SUDO)
How about creating the new key pair and then starting the testing process? Is it helpful? Because we can make sure there is no other vested balance available.

2023-03-10 10:00 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +def pallet_vesting_test():
Several points: 

1. Let us rename the function name first. The name vest_transfer_test is not good because the function's behavior only sends the function. It always makes me confused about why one test includes another test.
2. In best practice, we should use the second approach; however, let us use the first one because we need to finish this task sooner. And please leave a TODO or comment there.

2023-03-12 21:42 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +    vest_test(KP_TARGET_FIRST)
Improved the structure of the code. So that, now we can make exact comparison in the assert statement.

2023-03-12 21:42 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +    vest_other_test(KP_TARGET_SECOND, KP_SUDO)
Improved the structure of the code. So that, now we can make exact comparison in the assert statement.

2023-03-12 21:43 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +def pallet_vesting_test():
Updated code structure with TODO comment

2023-03-13 11:12 UTC, sfffaaa requested changes

2023-03-13 11:12 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +KP_SOURCE = Keypair.create_from_uri('//Bob')
If I remember correctly, we discussed using the brand-new KP for each test. Or we won't include it here.

2023-03-13 11:12 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +def pallet_vesting_test():
Oh, I found out that I didn't explain myself well. Please extract this function into three different test functions.
1. Testing function for vested_transfer --> vest
2. Testing function for force_vested_transfer --> vest_other
3. Testing function for merge_test
And please also make these three functions without any dependency

2023-03-13 12:48 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +KP_SOURCE = Keypair.create_from_uri('//Bob')
Since code structure and logic have been changed we do not need new key pair. full vested amount is released in the same test. At one point of time there will be only one vested amount in the KP_TARGET.

2023-03-13 14:05 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
>      result = substrate.query('System',
Code replaced with an already available function

2023-03-14 11:23 UTC, sfffaaa commented on tools/pallet_vesting_test.py
> +    merge_schedules(KP_SOURCE,
After doing the merged schedule, what should we test? Or we just check whether the extrinsic can work or not.

2023-03-20 14:14 UTC, sayyed-kamran commented on tools/pallet_vesting_test.py
> +    merge_schedules(KP_SOURCE,
Relevant assert statements added to verify correctness of merge schedules

2023-03-20 16:18 UTC, sfffaaa approved these changes

2023-03-20 16:22 UTC, merged