Feat/1205001926762628 introduce pytest
peaqnetwork/peaq-bc-test pull request #18
Opened 2023-08-02 09:53 UTC by sfffaaa

1. Introduce the pytest
2. Add token economy parameter tests
3. Refine some tests

2023-08-02 10:40 UTC, neutrinoks requested changes
Generally, I really like, that we improve the basic framework and structure of our integration-tests, BUT this will lead to some additional work for me because the ongoing work on Zenlink and the ParachainStaking-claim-mechanism... So it would have been better to look out for a better point of time, when upgrading the test-framework, but we will make it somehow :wink:

2023-08-02 10:40 UTC, neutrinoks commented on tools/utils.py
> +    if not block_hash:
There is no need for differentiation of `not block_hash`, because the `query` method's default for block_hash is also `None`. By defining `def get_account_balance(substrate, addr, block_hash=None)` and passing it to the query-method every upgrade is already done :wink:

2023-08-02 10:40 UTC, neutrinoks commented on tests/pallet_rbac_test.py
> +class PalletRBACTest(unittest.TestCase):
So far almost all test have the naming-pattern `Test...` so we should keep it here too -> `TestPalletRBAC` :blush:

2023-08-14 09:16 UTC, sfffaaa commented
After talking about it, I'll close this MR first. After Zenlink-related implementation is merge, I'll reopen and Merge this MR.

2023-09-18 05:30 UTC, neutrinoks commented on tests/zenlink_dex_test.py
> +        'interior': {'X1': {'Parachain': f'{PEAQ_PD_CHAIN_ID}'}}
I really like this constant's name :+1: because of the second EVM ID :blush:

2023-09-18 05:34 UTC, neutrinoks approved these changes
See my one comment on the test definition. We don*t need an order between the single integration tests anymore... up to you, if we want to change that :blush:

2023-09-18 05:34 UTC, neutrinoks commented on tests/zenlink_dex_test.py
>      def test_zenlink_dex(self):
Since my last changes, starting from Maryna's issue, I changed the inner logic of the tests that way, so that they can ran independently... So, we don't need an order of the single integration tests anymore... :blush: :+1:

2023-09-19 09:32 UTC, sfffaaa commented on tests/zenlink_dex_test.py
>      def test_zenlink_dex(self):
Cool! I'll extract the test cases in next feature branch

2023-09-19 09:33 UTC, merged