Feat/1203500610868804 rpc storage pallet
peaqnetwork/peaq-bc-test pull request #3
Opened 2023-01-02 11:30 UTC by talhadaar

- Implementation of integration test for peaq-pallet-storage's RPC. 
- Dependent on [PR](https://github.com/peaqnetwork/peaq-storage-pallet/pull/11) on peaq-pallet-storage.

2023-01-02 13:06 UTC, sfffaaa requested changes

2023-01-02 13:06 UTC, sfffaaa commented on tools/two_address_substrate_with_extrinsic.py
> +    # TODO RPC returns an array of bytes, not key-value struct as is expected.
Have we solved this TODO?

2023-01-02 13:06 UTC, sfffaaa commented on tools/two_address_substrate_with_extrinsic.py
> +            item = '0x032132'
Can you check whether the test case can pass when we run the test cases twice without restarting the blockchain? Because in test cases, we shouldn't have the side-effect. If it fails, please use a different item name every time. (maybe created based on the time)

2023-01-02 13:06 UTC, sfffaaa commented on tools/two_address_substrate_with_extrinsic.py
> +def pallet_storage_test():
I think it's better to extract it to the new file; what's your opinion?

2023-01-04 08:28 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +    # TODO RPC returns an array of bytes, not key-value struct as is expected.
Experimenting on this at the moment, will know soon.

2023-01-04 08:29 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +            item = '0x032132'
Looks like it's failing, i'll use the time based value.

2023-01-04 08:30 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +def pallet_storage_test():
I originally intended to, but didn't think the amount of code merited it. I will implement it now for better readability and maintenance.

2023-01-04 14:21 UTC, talhadaar commented on test.py
> +    # # pallet_batchall_test()
Looks like pallet_did_test fail due to a programmatic error which is why they are commented out. Uncommenting all of them for merger purposes, assuming pallet_did_tests are a WIP somewhere else.

2023-01-04 14:29 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +            item = '0x032132'
Using a random int value form 0 to 1024 instead as time can be less than 0.

2023-01-04 14:30 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +
Done, lint errors resolved auth autopep8.

2023-01-04 16:17 UTC, sfffaaa commented on test.py
> +    # # pallet_batchall_test()
Okay, I got it. Please create an asana task with a detailed message. I'll take a look.

2023-01-04 17:41 UTC, sayyed-kamran commented
I will suggest to change the name of the file from "pallet_storage_test.py" to some thing like pallet_storage_rbac_test. We will use the name pallet_storage_test for writing integration tests for pear_pallet_storage.  One more options will be, we may write peaq_pallet_storage integration test in the same file once theese changes are merged.

2023-01-05 12:57 UTC, talhadaar commented on test.py
> +    # # pallet_batchall_test()
Correction: Looks like error is in evm_rpc_test() not pallet_did_test() as I had originally mentioned.

2023-01-05 13:33 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +    # TODO RPC returns an array of bytes, not key-value struct as is expected.
Fixed!

2023-01-05 13:34 UTC, talhadaar commented on tools/two_address_substrate_with_extrinsic.py
> +            item = '0x032132'
FIX: using time based value instead now as a randint value sometimes leads to a key that is of invalid format

2023-01-05 13:35 UTC, talhadaar commented
> I will suggest to change the name of the file from "pallet_storage_test.py" to some thing like pallet_storage_rbac_test. We will use the name pallet_storage_test for writing integration tests for pear_pallet_storage. One more options will be, we may write peaq_pallet_storage integration test in the same file once theese changes are merged.

I will rename the file to pallet_storage_rpc_test.

2023-01-05 19:40 UTC, talhadaar commented
> I will suggest to change the name of the file from "pallet_storage_test.py" to some thing like pallet_storage_rbac_test. We will use the name pallet_storage_test for writing integration tests for pear_pallet_storage. One more options will be, we may write peaq_pallet_storage integration test in the same file once theese changes are merged.

I implemented the renaming in [this](https://github.com/peaqnetwork/peaq-bc-test/tree/feat/1203500610868804_rpc-storage-pallet-experiment) experiment branch, let me know if you can work with this.

2023-01-06 00:04 UTC, sayyed-kamran commented
> > I will suggest to change the name of the file from "pallet_storage_test.py" to some thing like pallet_storage_rbac_test. We will use the name pallet_storage_test for writing integration tests for pear_pallet_storage. One more options will be, we may write peaq_pallet_storage integration test in the same file once theese changes are merged.
> 
> I implemented the renaming in [this](https://github.com/peaqnetwork/peaq-bc-test/tree/feat/1203500610868804_rpc-storage-pallet-experiment) experiment branch, let me know if you can work with this.

Since you are writing sort of integration test too. Let us use one file with the name pallet_storage_test.py. I will copy my integration test code to this file as well, once I am done with it. It will make tracking things easy in future. All the integration tests of peaq_pallet_storage will be in one file.

2023-01-06 08:34 UTC, talhadaar commented
> > > I will suggest to change the name of the file from "pallet_storage_test.py" to some thing like pallet_storage_rbac_test. We will use the name pallet_storage_test for writing integration tests for pear_pallet_storage. One more options will be, we may write peaq_pallet_storage integration test in the same file once theese changes are merged.
> > 
> > 
> > I implemented the renaming in [this](https://github.com/peaqnetwork/peaq-bc-test/tree/feat/1203500610868804_rpc-storage-pallet-experiment) experiment branch, let me know if you can work with this.
> 
> Since you are writing sort of integration test too. Let us use one file with the name pallet_storage_test.py. I will copy my integration test code to this file as well, once I am done with it. It will make tracking things easy in future. All the integration tests of peaq_pallet_storage will be in one file.

Sounds cool! We can just work with the current changes then.

2023-01-06 09:05 UTC, sfffaaa approved these changes

2023-01-06 10:04 UTC, merged